services:
  llama-server:
    image: ghcr.io/ggml-org/llama.cpp:server-rocm
    container_name: llama-rocm
    stdin_open: true
    tty: true

    ports:
      - "8080:8080"

    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri

    group_add:
      - video
      - render

    security_opt:
      - seccomp=unconfined

    environment:
      HSA_OVERRIDE_GFX_VERSION: "11.5.1"
      HIP_VISIBLE_DEVICES: "0"

    volumes:
      - ${HOME}/LLMs:/LLMs
      - ${HOME}/LLMs/My_LLM_Wiki/configs:/configs:ro

    command: >
      --models-preset /configs/llama_server/server_rocm.ini
      --host 0.0.0.0
      --port 8080

    restart: "no"