services:
  llama-server:
    image: ghcr.io/ggml-org/llama.cpp:server-vulkan
    container_name: llama-server-vulkan
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
      
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card1:/dev/dri/card1
      
    volumes:
      - /usr/share/vulkan:/usr/share/vulkan:ro
      - /etc/vulkan:/etc/vulkan:ro
      - /home/aja@phenospex.local/LLMs/:/LLMs
      
    command: >
      --models-preset /LLMs/server.ini
      
    restart: "no"
