services:
  llama-server:
    image: ghcr.io/ggml-org/llama.cpp:server-vulkan
    container_name: llama-server-vulkan
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"

    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card1:/dev/dri/card1

    volumes:
      - /usr/share/vulkan:/usr/share/vulkan:ro
      - /etc/vulkan:/etc/vulkan:ro
      - ${HOME}/LLMs:/LLMs
      - ${HOME}/LLMs/My_LLM_Wiki/configs:/configs:ro

    environment:
      GGML_VULKAN_DEVICE: "0"
      VK_ICD_FILENAMES: /usr/share/vulkan/icd.d/radeon_icd.x86_64.json

    command: >
      --models-preset /configs/llama_server/server_vulkan.ini

    restart: "no"