services:
  llama-server:
    image: docker.io/kyuz0/amd-strix-halo-toolboxes:vulkan-radv
    container_name: llama-server-vulkan-radv

    stdin_open: true
    tty: true

    ports:
      - "8080:8080"

    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card1:/dev/dri/card1

    group_add:
      - video
      - render

    security_opt:
      - seccomp=unconfined

    ipc: host


    # environment:
    #   GGML_VULKAN_DEVICE: "0"
    #   VK_ICD_FILENAMES: /usr/share/vulkan/icd.d/radeon_icd.x86_64.json

    volumes:
      - /usr/share/vulkan:/usr/share/vulkan:ro
      - /etc/vulkan:/etc/vulkan:ro
      - ${HOME}/LLMs:/LLMs
      - ${HOME}/LLMs/My_LLM_Wiki/configs:/configs:ro

    working_dir: /LLMs

    command: >
      llama-server
      --models-preset /configs/llama_server/server_vulkan.ini
      --host 0.0.0.0
      --port 8080

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    networks:
      - llm-net

    restart: "no"

networks:
  llm-net:
    external: true
    name: llm-net