services:
  llama-server:
    image: docker.io/kyuz0/amd-strix-halo-toolboxes:vulkan-radv
    container_name: llama-server-vulkan-radv

    stdin_open: true
    tty: true

    ports:
      - "8080:8080"

    devices:
      - /dev/dri:/dev/dri

    group_add:
      - video
      - render

    security_opt:
      - seccomp=unconfined

    ipc: host

    ulimits:
      memlock:
        soft: -1
        hard: -1

    environment:
      GGML_VULKAN_DEVICE: "0"
      VK_ICD_FILENAMES: /usr/share/vulkan/icd.d/radeon_icd.x86_64.json

    volumes:
      - /usr/share/vulkan:/usr/share/vulkan:ro
      - /etc/vulkan:/etc/vulkan:ro
      - ${HOME}/LLMs:/LLMs
      - ${HOME}/LLMs/My_LLM_Wiki/configs:/configs:ro

    working_dir: /LLMs

    command: >
      llama-server
      --models-preset /configs/llama_server/server_vulkan.ini

    restart: "no"

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui

    ports:
      - "3001:8080"

    environment:
      OPENAI_API_BASE_URL: http://llama-server:8080/v1
      OPENAI_API_KEY: dummy
      WEBUI_AUTH: "false"

    volumes:
      - open-webui:/app/backend/data

    depends_on:
      - llama-server

    restart: unless-stopped

volumes:
  open-webui: