#[server]
host = 0.0.0.0
port = 8080
no-webui = false
jinja = true

#[context]
cache-type-k = q8_0
cache-type-v = q8_0
ctx-size = 62256
kv-unified = true

#[performance]
ngl = all
fa = on
threads = 10
threads-batch = 14
parallel = 1
no-mmap = true
fit = true
reasoning = false
split-mode = none
mlock = on



# ==========================
# QWEN 3.6
# ==========================

[Qwen3.6-35B-A3B-Q4_K_M]
model = /LLMs/Models/Qwen3.6/Qwen3.6-35B-A3B-APEX-I-Mini.gguf
ctx-size = 8200
reasoning = false


# ==========================
# QWEN 3.5
# ==========================
# --------------------

[Qwen3.5-4B-Q8_0]
model = /LLMs/Models/Qwen3.5/Qwen3.5-4B-Q8_0.gguf
ctx-size = 8200

# ==========================
# Gemma
# ==========================
# --------------------
[Gemma-4-26B-APEX-I-Compact]
model = /LLMs/Models/Gemma/gemma-4-26B-A4B-APEX-I-Compact.gguf
ctx-size = 8200
reasoning = false

[Gemma-4-26B-it-MXFP4]
model = /LLMs/Models/Gemma/gemma-4-26B-A4B-it-MXFP4_MOE_BF16.gguf
ctx-size = 8200
reasoning = false

# ==========================
# Others
# ==========================
# --------------------
[David-4B-Q8_0]
model = /models/Others/Darwin-4B-David.Q8_0.gguf
