[*]
host = 0.0.0.0
port = 8080
parallel = 1
no-webui = False

# Threads
threads = 8
threads-batch = 16

# Context & Cache
ctx-size = 64768
cache-type-k = f16
cache-type-v = f16
kv-unified = true

# Features
fit = true
reasoning = false
jinja = true
ngl = all
fa = on
split-mode = none
main-gpu = 0
mmap = off
mlock = on
gpu-layers = all

# ==========================
# QWEN 3.6
# ==========================

# --------------------------
[Qwen3.6-35B-A3B-APEX-Heretic-I]
model = /LLMs/Models/Qwen3.6/Qwen3.6-35B-A3B-uncensored-heretic-APEX-I-Quality.gguf
mmproj = /LLMs/Models/mmproj/Qwen3.6_35B_A3B-mmproj-BF16.gguf
temperature=1.0 
top-p = 0.95 
top-k = 20
min-p = 0.0
presence-penalty = 0.0

chat-template-kwargs = {"preserve_thinking": true}

spec-type            = ngram-mod
spec-ngram-mod-n-min = 8
spec-ngram-mod-n-max = 24
spec-draft-n-min     = 64

reasoning-budget = 200
reasoning-budget-message = "\n I have all the details. Let me answer now."

# --------------------------
[Qwen3.6-27B-IQ4_NEO]
model = /LLMs/Models/Qwen3.6/Qwen3.6-27B-NEO-CODE-2T-OT-IQ4_XS.gguf

chat-template-kwargs = {"preserve_thinking": true}

ctx-size = 68256
cache-type-k = q8_0
cache-type-v = q8_0

spec-type            = ngram-mod
spec-ngram-mod-n-min = 8
spec-ngram-mod-n-max = 24
spec-draft-n-min     = 64

reasoning-budget = 200
reasoning-budget-message = "\n I have all the details. Let me answer now."

# --------------------------
[Qwen3.6-27B-Q4_K_XL]
model = /LLMs/Models/Qwen3.6/Qwen3.6-27B-UD-Q4_K_XL.gguf

chat-template-kwargs = {"preserve_thinking": true}

ctx-size = 68256
cache-type-k = q8_0
cache-type-v = q8_0

temperature=0.7 
top-p = 0.80 
top-k = 20
min-p = 0.0
presence-penalty = 1.0 

spec-type            = ngram-mod
spec-ngram-mod-n-min = 8
spec-ngram-mod-n-max = 24
spec-draft-n-min     = 64

reasoning-budget = 200
reasoning-budget-message = "\n I have all the details. Let me answer now."

# ==========================
# Gemma4
# ==========================
# --------------------------
[Mythos-Gemma4-26B-A4B]
model = /LLMs/Models/mythos-26b-a4b-prism-pro-dq.gguf
mmproj = /LLMs/Models/mmproj/mmproj-mythos-26b-a4b-prism-pro.gguf

image-min-tokens  = 560
image-max-tokens  = 2240

# --------------------------
[Darwin-4B-Q6_K]
model = /LLMs/Models/Others/Darwin-4B-David.Q6_K.gguf


# ==========================
# QWEN 3.5
# ==========================

# --------------------------
[Qwen3.5-35B-A3B-APEX-I]
model = /LLMs/Models/Qwen3.6/Qwen3.5-35B-A3B-Claude-Distilled-APEX-I-Quality.gguf
mmproj = /LLMs/Models/mmproj/Qwen3.6_35B_A3B-mmproj-BF16.gguf
temperature=1.0 
top-p = 0.95 
top-k = 20
min-p = 0.0
presence-penalty = 0.0 

chat-template-kwargs = {"preserve_thinking": true}

spec-type            = ngram-mod
spec-ngram-mod-n-min = 8
spec-ngram-mod-n-max = 24
spec-draft-n-min     = 64

reasoning-budget = 200
reasoning-budget-message = "\n I have all the details. Let me answer now."

# --------------------------
[Qwen3.5-35-A3B-MXFP4]
model = /LLMs/Models/Qwen3.5/Qwen3.5-35B-A3B-MXFP4_MOE.gguf


# --------------------------
[Huihui-Qwen3.5-35B-A3B]
model = /LLMs/Models/Qwen3.5/Huihui-Qwen3.5-35B-A3B-Claude-4.6-Opus-abliterated-MXFP4_MOE.gguf

# --------------------------
[Qwen3.5-122B-A10B-APEX]
model = /LLMs/Models/Qwen3.5/Qwen3.5-122B-A10B-APEX-I-Mini.gguf
temperature=1.0 
top-p = 0.95 
top-k = 20
min-p = 0.0
presence-penalty = 1.5 

ctx-size = 68256
cache-type-k = q8_0
cache-type-v = q8_0

#n-expert-used = 4
chat-template-kwargs = {"preserve_thinking": true}

spec-type            = ngram-mod
spec-ngram-mod-n-min = 24
spec-ngram-mod-n-max = 8
spec-draft-n-min     = 48
spec-draft-n-min     = 64

reasoning-budget = 200
reasoning-budget-message = "\n I have all the details. Let me answer now."
